<a href="https://colab.research.google.com/github/tejaNRI-Degree/Python-Mini-Project/blob/main/Introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
#Numpy - Numeric python
#Most powerful package - Library

#Numpy - Dimensions

#A-One Dimensions Array
#[A,B] || [A
#           B] - Two Dimensions Array -Row || column
#Three Dimensional

#Array-storing,Monipulating,similar Data type

#Faster than any mathematical functions
#convinient compared to other packages
#Memory efficiency
#Support multi dimensional array

#speed(Numpy operations) > speed(Lists operations)
#size(Numpy operations) < size (lists operations)
#Memory optimization (Numpy)> Memory optimization (Lists operations)

In [13]:
#Install numpy - pip3 install numpy // pip install numpy

In [14]:
import numpy as np

In [8]:
#create a numpy array
#1D array

arr1D =np.array([1,2,3,4,5])
print (arr1D)

[1 2 3 4 5]


In [30]:
#creating 2D array - Matrix
arr2D = np.array ([
       [1,2,3],[4,5,6]
])
print(arr2D)

[[1 2 3]
 [4 5 6]]


In [39]:

# Creating Arrays with default values

# Creating matrix with all values of elements as '0'
allZeros=np.zeros((2,3))
print(allZeros)

# Creating matrix with all values of elements as '0'
allOnes=np.ones((2,3))
print(allOnes)

# Creating matrix with all value of elements 'constant value' - n ~ Fill value'
allConstant=np.full((2,3),6)
print(allConstant)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[6 6 6]
 [6 6 6]]


In [48]:

# Create an identity matrix - I - Square matrix

identity= np.eye(4)
print(identity)

# Identity Matrix - Aii = 1 && Aij = 0
# For all A Belongs to R MxN
# Aij -

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [49]:

# Creating random Matrices

# with 0 and 1
rand1 = np.random.rand(3,3)
print(rand1)

# between a and b
rand2 = np.random.randint(10,20,(3,3))
print(rand2)

[[0.61018843 0.95103006 0.77771742]
 [0.91456184 0.32632933 0.86937456]
 [0.35178834 0.01611571 0.41116326]]
[[16 15 12]
 [17 17 19]
 [10 12 13]]


In [76]:
#Array ProPerties

arr = np.array([[1,2,3,4],[2,3,4,5]])
print(arr)

#Shape or array
print(f'\nThe shape of the arrays {arr.shape}')

#Size of array
print(f'The size of the array is {arr.size}')

#Datatype of array
print(f'The Data type of the array is {arr.dtype}')

#Dimensions of array
print (f'The Dimensions of the array is {arr.ndim}')

[[1 2 3 4]
 [2 3 4 5]]

The shape of the arrays (2, 4)
The size of the array is 8
The Data type of the array is int64
The Dimensions of the array is 2


In [53]:
# Indexing and Slicing

# Acess the elements in 1D Array

arr= np.array([1,2,3,4])
print(arr)
print(arr[3])

#Slicing the elements
print(arr[0:3])

#Acess the elements in 2D Array
arr2 = np.array([[1,2,3],[2,3,4]])
print(arr2)
print(arr2[1,1])
print(arr2[0,:]) #first row with all columns
print(arr2[:,0]) #first column with all rows

[1 2 3 4]
4
[1 2 3]
[[1 2 3]
 [2 3 4]]
3
[1 2 3]
[1 2]


In [61]:
#l1 = []
#[l1.append(_) for _ in range (10)]

l1 = np.arange(10,0,-1)
print(l1)

[10  9  8  7  6  5  4  3  2  1]


In [68]:
 # Mathematical operations
import numpy as np
a = np.array([1,2,3])
b = np.array([3,4,5])

print (f'The sum of a and b is {a+b}')
print (f'The diff of a and b is {a-b}')
print (f'The product of a and b is {a*b}')
print (f'The division of a and b is {a/b}')

The sum of a and b is [4 6 8]
The diff of a and b is [-2 -2 -2]
The product of a and b is [ 3  8 15]
The division of a and b is [0.33333333 0.5        0.6       ]


In [71]:
#Matrix Multiplication
import numpy as np
b1 = np.array([[1,2,3],[2,3,4]])
b2 = np.array([[5,6],[7,8],[1,3]])

#Dot product  --- product = AB -- A  m  n x n  -- B n x p
c = np.dot(b1,b2)
print (c)

[[22 31]
 [35 48]]


In [74]:
print(b1)

[[1 2 3]
 [2 3 4]]


In [75]:
print(b2)

[[5 6]
 [7 8]
 [1 3]]
