<a href="https://colab.research.google.com/github/tejaNRI-Degree/Python-Mini-Project/blob/main/Introduction_to_numpyS2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [65]:
import numpy as np

In [66]:
# Recap
arr = np.array([[1,2,3],[4,5,6]])

In [67]:
type (arr)

numpy.ndarray

In [68]:
#Dot product - m x n || n x p
arr1 = np.random.randint(1,2,(1,2))

In [69]:
arr.shape
arr1.shape

(1, 2)

In [70]:
result = np.dot(arr1,arr)

In [71]:
print(result)

[[5 7 9]]


In [72]:
r1 = np.random.randint(10,20,(3,3))
print (r1)

[[13 18 11]
 [13 18 17]
 [10 16 16]]


In [73]:
r2 = np.eye(3)
print (r2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [74]:
# r1.I
result2 = np.dot(r1,r2)

In [75]:
print(result2)

[[13. 18. 11.]
 [13. 18. 17.]
 [10. 16. 16.]]


In [76]:
#Mathematical Operations
# +-*/
t1 = np.random.randint(3,6,(3,3))
t2 = np.random.randint(3,6,(3,3))

In [77]:
print(t1)
print(t2)

[[5 4 4]
 [4 5 5]
 [4 5 3]]
[[3 5 4]
 [3 5 5]
 [5 3 5]]


In [79]:
t3 = t1*t2
print(t3)

[[15 20 16]
 [12 25 25]
 [20 15 15]]


In [81]:
#Matrix multiplication
result=np.dot(arr1,arr)

In [83]:
#Statistical operations
mean=t3.mean()
max=t3.max()
median=np.median(t3)
std=np.std(t3)
var=np.var(t3)

In [92]:
print(max)

25


In [93]:
print(median)

16.0


In [84]:
print(var)

19.209876543209877


In [85]:
print(std)

4.382907316292449


In [86]:
std *std

19.209876543209873

In [89]:
# Trigonometric functions

#sin(x)
#cos(x)
#Tan(x) - sin(x) / cos(x)
#cosec - 1 / sin(x)
#sec - 1 / cos(x)
#cot - 1 / tan(x)
#
angles = np.array([0,15,30,45,60,75,90])

#sin (array)

result = np.sin(np.radians(angles))
result1 = np.cos(np.radians(angles))
result2 = np.tan(np.radians(angles))

In [90]:
print(result)
print(result1)
print(result2)

[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
[1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]


In [91]:
arr = np.array([1,2,3,4,5,6])

#Reshape the array
reshapedarr = arr.reshape(3,2)

print (reshapedarr)

# Convert / Flatten any n dim array
flattenedarr = arr.flatten()

print (flattenedarr)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [99]:
#Stacking the data

arr1 = np.array([1,2,3,4])
arr2 = np.array([10,20,30,40])

#Vertical Stacking
arr3 = np.vstack([arr1,arr2])
print(f"The shape of arr3 is {arr3.shape}")

#Horizantal Stacking
arr4 = np.hstack([arr1,arr2])
print(f"The shape of arr4 is {arr4.shape}")
print(arr4)

The shape of arr3 is (2, 4)
The shape of arr4 is (8,)
[ 1  2  3  4 10 20 30 40]


In [100]:
#Filtering
arr = np.array([10,20,30,40,50,60,70,80])

farr = arr[arr >40]

print (farr)

[50 60 70 80]
